version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: appdsi-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Ces volumes persistants permettront de ne pas perdre vos données SQLite
      # ni vos fichiers PDF / Excel lors d'un redémarrage ou d'une mise à jour du container.
      - sqlite_data:/app
      - uploads_data:/app/uploads
      - commandes_data:/app/file_commandes
      - factures_data:/app/file_factures
      - certif_data:/app/file_certif

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: appdsi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
  uploads_data:
  commandes_data:
  factures_data:
  certif_data:
